### ISSUE TITLE
Hello Anthony

### ISSUE THREAD

**Issue by armoner** [AryToNeX/pinkpill#1]
Thanks for another fucking solution that nobody asked. A fucking demon using web technologies? What a fucking joke. You could do it using scripts. Nobody wants your shit plus you will never be a woman fucking abomination. Go shill about your shitty projects on Reddit (oh wait, you already did that).

Is that what you wanted, right? Some attention BTFO abomination your parents will use your real name when they bury you.

**Comment by AryToNeX** [comment]
I love you too!

**Comment by AryToNeX** [comment]
and by the way I get it, this could be done in POSIX shell. I did it this way for the meme and I even wrote it in the Reddit post.

Also, nope dude, wrong person, I do not care if you come here saying shit about me, I am not that desperate, but thanks for trying
